app = 'crypto-trading-assistant'
primary_region = 'sin'

[build]

[env]
LOG_LEVEL = "INFO"

[deploy]
strategy = "immediate"

[[services]]
internal_port = 8080
protocol = "tcp"
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1

[[services.http_checks]]
interval = "30s"
timeout = "5s"
grace_period = "10s"
method = "GET"
path = "/health"

[[vm]]
memory = 512
cpu_kind = "shared"
cpus = 1